language: c
branches:
  only:
  - master
script: ./travis-tool.sh run_tests
before_script:
  - sudo apt-get update
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo R CMD javareconf
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package testthat
notifications:
  email:
    - christopher.gandrud@gmail.com
